"""Compute regulatory noise-impact zones from precomputed pile-driving
transmission-loss (TL) model output, via the ns_pile_driving_noise_mapping
package maintained separately at NOISE_IMPACT_CODE_DIR (see that package's
own README for the underlying acoustic model and its Noise_Impact_Thresholds
workbook of NOAA/NMFS regulatory thresholds).

This wraps the package's calculate_noise_impact() — its public, plot-free
entry point — and converts its output into JSON/GeoJSON, since that package
returns numpy arrays, an xarray Dataset, and a pandas DataFrame, none of
which are directly servable over HTTP.

Site selection is a hard constraint, not a UI choice pretending otherwise:
each entry in SITES corresponds to a transmission-loss model that was
already run offline (CSnap, per-azimuth) for a fixed source location,
depth, frequency, and date. There is currently no way to compute impact
zones for an arbitrary point — only for these precomputed scenarios.
Running the propagation model itself is a separate, much slower offline
process outside the scope of this API.

Real vs. fixture data
----------------------
The real package (178KB) plus its real CSnap transmission-loss data
(~950MB, just for these 2 sites) normally live at /home/shared, a path
specific to the machine this was developed on — too large to commit to
git, and not present on e.g. a laptop with no access to that shared
mount. So this module falls back to a small vendored copy of the package
(mock_api/vendor) and synthetic fixture CSnap data (mock_api/
noise_impact_fixtures, generated by mock_api/seed_noise_impact_fixtures.py
— NOT real acoustic model output, see that script's docstring) whenever
the real /home/shared paths aren't present, purely so the app runs
end-to-end for local UI development. IS_USING_FIXTURE_DATA and
list_sites()/compute_impact()'s "using_fixture_data" fields surface this
to the frontend so fake data is never silently presented as real.
"""

import os
import sys
import threading
from datetime import date, timedelta

import numpy as np  # type: ignore
from shapely.geometry import Polygon, mapping  # type: ignore

_REAL_CODE_DIR = "/home/shared/noise_impact_code"
_VENDORED_CODE_DIR = os.path.join(os.path.dirname(__file__), "..", "mock_api", "vendor")

NOISE_IMPACT_CODE_DIR = os.environ.get("NOISE_IMPACT_CODE_DIR")
if not NOISE_IMPACT_CODE_DIR:
    NOISE_IMPACT_CODE_DIR = _REAL_CODE_DIR if os.path.isdir(_REAL_CODE_DIR) else _VENDORED_CODE_DIR
sys.path.insert(0, NOISE_IMPACT_CODE_DIR)

from ns_pile_driving_noise_mapping import (  # noqa: E402 # type: ignore
    ExposureAssessmentParams, TLModelParams, NoiseLevelParams,
    HearingGroup, Impact, Metric,
)
from ns_pile_driving_noise_mapping.core import calculate_noise_impact  # noqa: E402 # type: ignore
import ns_pile_driving_noise_mapping.core as _npnm_core  # noqa: E402 # type: ignore


# Cache the multi-second CSnap TL-pickle load (see compute_impact's
# docstring). Keyed on the fields that determine what's actually read from
# disk -- site's data_folder/depth/freq/date, all fixed per SITES entry --
# not on exposure/noise-level params, since those are what users actually
# vary between runs for the same site (SPL, strikes, hearing groups, etc.)
# and don't change what load_tl_model_output would read.
#
# Implemented as a monkeypatch of core's module-level reference to
# load_tl_model_output (bound there via `from .io.tl_model import
# load_tl_model_output`) rather than reimplementing calculate_noise_impact's
# internals with its private helpers -- keeps this decoupled from a package
# still under active development elsewhere, per that docstring's stated
# reason for not caching sooner. Fragile in one way: if the package ever
# changes how core.py imports/calls that function, this patch silently
# stops applying (falls back to uncached, not a crash) -- worth re-checking
# after any ns_pile_driving_noise_mapping upgrade.
_load_tl_model_output_uncached = _npnm_core.load_tl_model_output
_tl_model_cache: dict[tuple, dict] = {}
_tl_model_cache_lock = threading.Lock()


def _cached_load_tl_model_output(tl_model_params):
    key = (
        os.path.normpath(str(tl_model_params.data_folder)),
        tl_model_params.src_depth,
        tl_model_params.src_freq,
        tl_model_params.noise_date,
    )
    with _tl_model_cache_lock:
        cached = _tl_model_cache.get(key)
    if cached is not None:
        return cached
    result = _load_tl_model_output_uncached(tl_model_params)
    with _tl_model_cache_lock:
        _tl_model_cache[key] = result
    return result


_npnm_core.load_tl_model_output = _cached_load_tl_model_output


# Cache PolarFieldInterpolator construction too. Profiling showed this --
# not the TL-pickle load above -- is the actual dominant cost per request
# (~4s of ~5s for a real-data site): it builds a Delaunay triangulation
# over a 500x500 lon/lat grid, but only depends on the source's azimuth/
# distance coordinates and src_lon/src_lat, none of which vary with
# exposure_params or noise_level_params. calculate_noise_impact() builds it
# unconditionally (it's attrs["GridMapper"], meant for create_map's
# plotting path) even though compute_impact() below never plots and never
# reads that attribute -- so this was pure waste on every request before
# caching, independent of the TL-load question.
#
# Keyed on (src_lon, src_lat, azimuth values) rather than reusing the
# TL-load cache key above because this wrapper only receives the Dataset
# actually passed at the PolarFieldInterpolator(...) call site in core.py,
# not the tl_model_params object -- but for a given site, azimuth/distance
# coordinates are untouched by every step between the TL load and this
# call (depth-averaging and RL-weighting only touch the "depth" dimension
# and add data_vars), so they're a reliable stand-in for "same site".
_PolarFieldInterpolator_uncached = _npnm_core.PolarFieldInterpolator
_interpolator_cache: dict[tuple, object] = {}
_interpolator_cache_lock = threading.Lock()


def _cached_polar_field_interpolator(ds, src_lon, src_lat, *args, **kwargs):
    key = (
        float(src_lon),
        float(src_lat),
        tuple(np.asarray(ds.azimuth.values).tolist()),
        args,
        tuple(sorted(kwargs.items())),
    )
    with _interpolator_cache_lock:
        cached = _interpolator_cache.get(key)
    if cached is not None:
        return cached
    result = _PolarFieldInterpolator_uncached(ds, src_lon, src_lat, *args, **kwargs)
    with _interpolator_cache_lock:
        _interpolator_cache[key] = result
    return result


_npnm_core.PolarFieldInterpolator = _cached_polar_field_interpolator


_FIXTURES_ROOT = os.path.join(os.path.dirname(__file__), "..", "mock_api", "noise_impact_fixtures")


def _data_folder(real_path: str, fixture_subdir: str) -> str:
    """Real CSnap data if this machine has it mounted, else the small
    synthetic fixture for the same site — see module docstring."""
    return real_path if os.path.isdir(real_path) else os.path.join(_FIXTURES_ROOT, fixture_subdir)


# Each site is a transmission-loss model already run offline for a fixed
# source location/depth/frequency/date — see module docstring. Paths point
# at CSnap pickle output under /home/shared/pileDrivingSoundPropagation/,
# falling back to synthetic fixture data if that's not present.
SITES = {
    "French Bank": dict(
        data_folder=_data_folder(
            "/home/shared/pileDrivingSoundPropagation/testFrenchBank/output/modelRun/csnapOut/",
            "french_bank",
        ),
        src_freq=100, src_depth=135,
        src_lon=-61.477536, src_lat=44.6143972,
        noise_date=date(2020, 7, 15),
    ),
    "Sydney Bight": dict(
        data_folder=_data_folder(
            "/home/shared/pileDrivingSoundPropagation/sydneyBight/output/modelRun/csnapOut/",
            "sydney_bight",
        ),
        src_freq=100, src_depth=45,
        src_lon=-59.82201388888889, src_lat=46.522622222222225,
        noise_date=date(2020, 7, 15),
    ),
}


def _is_fixture(site: str) -> bool:
    return os.path.normpath(SITES[site]["data_folder"]).startswith(os.path.normpath(_FIXTURES_ROOT))


def list_sites() -> dict:
    """Site metadata for the frontend dropdown — everything except the
    on-disk data_folder, which is a backend implementation detail."""
    return {
        name: {
            "src_lon": cfg["src_lon"],
            "src_lat": cfg["src_lat"],
            "src_depth": cfg["src_depth"],
            "src_freq": cfg["src_freq"],
            "noise_date": cfg["noise_date"].isoformat(),
            "using_fixture_data": _is_fixture(name),
        }
        for name, cfg in SITES.items()
    }


def list_options() -> dict:
    """Available hearing groups / impact types / metrics, straight from the
    package's enums — so the frontend never hardcodes a list that could
    drift from Noise_Impact_Thresholds.xlsx."""
    return {
        "hearing_groups": [g.value for g in HearingGroup],
        "impact_types": [i.value for i in Impact],
        "metrics": [m.value for m in Metric],
    }


def compute_impact(
    site: str,
    hearing_groups: list[str],
    impact_types: list[str],
    metrics: list[str],
    depth_range: tuple[float, float],
    spl_peak: float,
    sel_single_strike: float,
    n_strikes_per_pile: int,
    n_piles: int,
    assessment_period_hours: float,
) -> dict:
    """Run the impact model for one site and return JSON-serializable zones:

        {"source": {"lon": ..., "lat": ...},
         "zones": [{"hearing_group", "impact", "metric", "threshold_db",
                     "area_km2", "geometry"} , ...]}

    `geometry` is a GeoJSON Polygon, or None if the threshold was never
    exceeded anywhere (zero-area zone — nothing to draw).

    depth_range uses the package's own sign convention: negative metres
    below the surface (0 at the surface), matching the CSnap depth
    coordinate — e.g. (-40.0, -0.01) for "near-surface down to 40m".

    The (multi-second) TL-pickle load is cached per site — see the
    monkeypatch of load_tl_model_output above. Everything downstream
    (depth-averaging, received-level weighting, zone boundaries) still runs
    fresh every call, since that's what actually depends on
    exposure_params/noise_level_params.
    """
    if site not in SITES:
        raise ValueError(f"Unknown site: {site}")

    tl_model_params = TLModelParams(model_name=site, **SITES[site])
    exposure_params = ExposureAssessmentParams(
        hearing_groups=hearing_groups,
        impact_types=impact_types,
        metrics=metrics,
        depth_range=depth_range,
    )
    noise_level_params = NoiseLevelParams(
        SPL_peak=spl_peak,
        SEL_single_strike=sel_single_strike,
        n_strikes_per_pile=n_strikes_per_pile,
        n_piles=n_piles,
        assessment_period=timedelta(hours=assessment_period_hours),
    )

    result = calculate_noise_impact(exposure_params, tl_model_params, noise_level_params)

    zones = []
    for zone, th_row in zip(result["zone_data"], result["df_th"].itertuples()):
        geometry = None
        if float(zone["Distance"].max()) > 0:
            coords = list(zip(zone["Longitude"].tolist(), zone["Latitude"].tolist()))
            geometry = mapping(Polygon(coords))
        zones.append({
            "hearing_group": str(th_row.HearingGroup),
            "impact": str(th_row.Impact),
            "metric": str(th_row.Metric),
            "threshold_db": float(th_row.Threshold_dB),
            "area_km2": float(zone["Area"]) / 1e6,
            # Mean/std of the raw per-azimuth Distance array, in km -- same
            # "Radius = mean ± std" convention ns_pile_driving_noise_mapping's
            # own create_map() legend uses (visualization/mapping.py:560-561),
            # not an equivalent-circle-from-area approximation, so numbers
            # shown here match what that package's own plots would show.
            "radius_km": float(zone["Distance"].mean()) / 1000,
            "radius_std_km": float(zone["Distance"].std()) / 1000,
            "geometry": geometry,
        })

    return {
        "source": {"lon": tl_model_params.src_lon, "lat": tl_model_params.src_lat},
        "using_fixture_data": _is_fixture(site),
        "zones": zones,
    }
